require_relative 'animal'
require_relative 'mammal'
require_relative 'amphibian'
require_relative 'bat'
require_relative 'primate'
require_relative 'chimpanzee'
require_relative 'frog'
require_relative 'parrot'